fb1-5:  fb1-5.l fb1-5.y
    bison -b parser.y -d fb1-5.y
    flex lexer.l
    cc lex.yy.c -ll
    notepad
    gcc -o fb1-5 fb1-5.tab.c lex.yy.c -lfl -ly -Wfatal-errors

# New:
    bison -d -o ./ObjectFiles/parser.tab.c parser.y                                     # Generates parser.tab.c and parser.tab.h in ./ObjectFiles

    flex -o ./ObjectFiles/lex.yy.c lexer.l                                              # Generates lex.yy.c in ./ObjectFiles

    g++ -c ./ObjectFiles/parser.tab.c -o ./ObjectFiles/parser.tab.o                     # Compiles the generated C files into object files inside ./ObjectFiles
    g++ -c ./ObjectFiles/lex.yy.c -o ./ObjectFiles/lex.yy.o                             # Compiles the generated C files into object files inside ./ObjectFiles

    g++ -c src/main.cpp -o ./ObjectFiles/main.O                                         # Make the rest of the interpreter an object inside ./ObjectFiles

    g++ -o ./build/MagiLangInterpreter \                                                #Make final exe MagiLangInterpreter
    ./ObjectFiles/main.o \
    ./ObjectFiles/parser.tab.o \
    ./ObjectFiles/lex.yy.o \
    -lfl -ly -Wfatal-errors
